# Pull V4 crawler base image from dockerhub norconex public registry
FROM 4.0.0-crawler

# Pull the v4 committer package from Maven or internet
WORKDIR /nxer

RUN ls -l && \
    mkdir test-folder && \
    ls -l
