FROM replace-this-with-real-version-crawler-base
ARG committer_type
ARG build_version

RUN echo "committer type is: $committer_type"
RUN echo "build_version is: $build_version"

WORKDIR /nxer

RUN ls -l

RUN replace-this-with-committer-files-in-dockerfile

#RUN if [ "$committer_type" = "crawler-es" ]; then \
      #COPY $committer_type /nxer && \
	  #mkdir /nxer/es_folder && \
          #echo "es copy"; \
	#elif [ "$committer_type" = "crawler-solr" ]; then \
          #echo "solr copy" && \
         # COPY fakefile . && \
	  #mkdir /nxer/solr-folder; \
	#else \
      #echo "other committers to copy" && \
	#  mkdir /nxer/other-copy; \
	#fi


RUN ls -l
