#!/bin/bash

# Returns the maven parameters required to run a mvn command only 
# on projects with changed files. If the Maven parent project was modified,
# an empty string is returned (i.e., a regular maven build on parent without 
# project filtering).
#
# Relies on  ./github/outputs/all_changed_files.txt to be present, 
# generated by 'tj-actions/changed-files' action.


OUTPUTS_DIR=$GITHUB_ACTION_PATH/.github/outputs
CHANGES_FILE=all_changed_files.txt

parent_changed=$(cd $OUTPUTS_DIR && cat $CHANGES_FILE | grep -v -e ^committer -e ^importer -e ^crawler | wc -l)

if [ $parent_changed -gt 0 ]; then
    # maven parent has changed, so don't filter to build all projects
    echo "";
    exit;
fi

# Filter on modified artifacts
artifacts=$(cd $OUTPUTS_DIR && cat $CHANGES_FILE | tr ' ' '\n' | grep -e ^committer -e ^importer -e ^crawler | sed 's_^\(committer\|crawler\)/\(.*\)$_:\1-\2_' | sed 's_^\(importer\)/.*$_:\1_' | sort | uniq | tr '\n' ' ')
echo "--projects $artifacts"
