#!/bin/bash

# Returns the maven parameters required to run a mvn command only 
# on projects with changed files. If the Maven parent project was modified,
# an empty string is returned (i.e., a regular maven build on parent without 
# project filtering).
#
# Relies on  ./github/outputs/all_changed_files.txt to be present, 
# generated by 'tj-actions/changed-files' action.
#
# Expects 1 argument which is the GitHub Action trigger event name
# (e.g., "push", "pull_request"). 

if [ $# -eq 0 ]; then
    echo "Missing GitHub Action trigger event name argument.";
    exit -1; 
fi

GHA_EVENT=$1
OUTPUTS_DIR=.github/outputs
CHANGES_FILE=all_changed_files.txt

# If Maven parent changed, build all, else, filter on changed projects

parent_changed=$(cd $OUTPUTS_DIR && cat $CHANGES_FILE \
    | grep -v -e ^committer -e ^importer -e ^crawler \
    | wc -l)

mvn_phase=verify
if [ $GHA_EVENT == "push" ]; then
    mvn_phase=deploy
fi

mvn_projects=""
if [ $parent_changed -eq 0 ]; then
    # Filter on modified artifacts
    artifacts=$(cd $OUTPUTS_DIR && cat $CHANGES_FILE \
        | tr ' ' '\n' \
        | grep -e ^committer -e ^importer -e ^crawler \
        | sed 's_^\(committer\|crawler\)/\(.*\)$_:nx-\1-\2_' \
        | sed 's_^\(importer\)/.*$_:nx-\1_' \
        | sort \
        | uniq \
        | tr '\n' ' ')
    mvn_projects="--projects $artifacts"
fi

# return command so it can be logged by GHA workflow
echo "mvn clean $mvn_phase org.sonarsource.scanner.maven:sonar-maven-plugin:sonar $mvn_projects -amd --threads=2 --batch-mode";
