FROM replace-this-with-real-version
ARG committer_type
ARG dl_filename
ARG committer_version
ARG build_version
ARG crawler_type

WORKDIR /nxer

COPY downloaded/$committer_type/*.zip .
RUN unzip ${dl_filename}
RUN cp nx-committer-${committer_type}-${committer_version}/lib/* nx-crawler-${crawler_type}-${build_version}/lib/
RUN rm *.zip
